export const AUDIT_ACTION_LABELS: Record<string, string> = {
  "user.create": "Alta de usuario",
  "user.update": "Edición de usuario",
  "user.suspend": "Suspensión de usuario",
  "user.reactivate": "Reactivación de usuario",
  "user.password_reset": "Cambio de contraseña",
  "permission.assignment_change": "Cambio de roles asignados",
  "permission.role_change": "Cambio de permisos de rol",
  "role.create": "Alta de rol",
  "role.delete": "Baja de rol",
  "branch.create": "Alta de sucursal",
  "branch.update": "Edición de sucursal",
  "branch.status_change": "Cambio de estado de sucursal",
  "team.create": "Alta de equipo",
  "team.update": "Edición de equipo",
  "team.members_change": "Cambio de miembros de equipo",
  "organization.update": "Cambio de configuración",
  "contact.create": "Alta de contacto",
  "contact.update": "Edición de contacto",
  "contact.delete": "Baja de contacto",
  "contact.assignment_change": "Cambio de responsable de contacto",
  "contact.merge": "Fusión de contactos",
  "contact.duplicate_dismissed": "Duplicado descartado",
  "lead.create": "Alta de lead",
  "lead.status_change": "Cambio de etapa de lead",
  "lead.assignment_change": "Reasignación de lead",
  "lead.search_update": "Cambio de búsqueda",
  "owner.create": "Alta de propietario",
  "owner.update": "Edición de propietario",
  "owner.financial_update": "Cambio de datos bancarios",
  "owner.financial_view": "Consulta de cuenta bancaria",
  "property.create": "Alta de propiedad",
  "property.update": "Edición de propiedad",
  "property.status_change": "Cambio de estado de propiedad",
  "property.assignment_change": "Cambio de responsable de propiedad",
  "property.price_change": "Cambio de precio",
  "property.owner_change": "Cambio de propietarios",
  "property.media_add": "Alta de foto o video",
  "property.media_update": "Edición de foto",
  "property.media_reorder": "Reordenamiento de fotos",
  "property.media_cover": "Cambio de portada",
  "property.media_delete": "Baja de foto o video",
  "acquisition.create": "Alta de captación",
  "acquisition.update": "Edición de captación",
  "acquisition.stage_change": "Cambio de etapa de captación",
  "valuation.create": "Alta de tasación",
  "document.upload": "Carga de documento",
  "document.update": "Edición de documento",
  "document.delete": "Baja de documento",
  "document.download": "Descarga de documento",
};

export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  user: "Usuario",
  role: "Rol",
  branch: "Sucursal",
  team: "Equipo",
  organization: "Organización",
  contact: "Contacto",
  lead: "Lead",
  property: "Propiedad",
  acquisition: "Captación",
  valuation: "Tasación",
  document: "Documento",
};

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action;
}
