/**
 * Catálogo geográfico inicial de Uruguay. Los 19 departamentos están completos; las
 * localidades y barrios cubren los mercados principales (Montevideo, Maldonado, Canelones)
 * y las capitales departamentales. Es un punto de partida editable, no un padrón oficial.
 */

export interface GeoLocalitySeed {
  name: string;
  neighborhoods?: string[];
}

export const URUGUAY_GEO: Record<string, GeoLocalitySeed[]> = {
  Artigas: [{ name: "Artigas" }, { name: "Bella Unión" }],
  Canelones: [
    { name: "Canelones" },
    {
      name: "Ciudad de la Costa",
      neighborhoods: [
        "Parque Carrasco",
        "Shangrilá",
        "San José de Carrasco",
        "Lagomar",
        "Solymar",
        "Lomas de Solymar",
        "Colinas de Solymar",
        "El Pinar",
      ],
    },
    { name: "Atlántida", neighborhoods: ["Centro", "Villa Argentina", "Estación Atlántida"] },
    { name: "Las Piedras" },
    { name: "Pando" },
    { name: "La Paz" },
    { name: "Progreso" },
    { name: "Santa Lucía" },
    { name: "Parque del Plata" },
    { name: "La Floresta" },
    { name: "Salinas" },
    { name: "Barros Blancos" },
    { name: "Toledo" },
    { name: "Sauce" },
  ],
  "Cerro Largo": [{ name: "Melo" }, { name: "Río Branco" }],
  Colonia: [
    { name: "Colonia del Sacramento" },
    { name: "Carmelo" },
    { name: "Nueva Helvecia" },
    { name: "Juan Lacaze" },
  ],
  Durazno: [{ name: "Durazno" }],
  Flores: [{ name: "Trinidad" }],
  Florida: [{ name: "Florida" }],
  Lavalleja: [{ name: "Minas" }],
  Maldonado: [
    { name: "Maldonado", neighborhoods: ["Centro", "Barrio Norte", "Cerro Pelado", "Las Delicias"] },
    {
      name: "Punta del Este",
      neighborhoods: [
        "Península",
        "Playa Mansa",
        "Playa Brava",
        "Aidy Grill",
        "San Rafael",
        "Cantegril",
        "Rincón del Indio",
        "Pinares",
        "Beverly Hills",
        "Lugano",
      ],
    },
    { name: "Piriápolis", neighborhoods: ["Centro", "Playa Hermosa", "Playa Grande", "Punta Colorada"] },
    { name: "San Carlos" },
    { name: "Pan de Azúcar" },
    { name: "Aiguá" },
    { name: "La Barra" },
    { name: "José Ignacio" },
  ],
  Montevideo: [
    {
      name: "Montevideo",
      neighborhoods: [
        "Aguada",
        "Aires Puros",
        "Atahualpa",
        "Barrio Sur",
        "Bella Vista",
        "Belvedere",
        "Brazo Oriental",
        "Buceo",
        "Capurro",
        "Carrasco",
        "Carrasco Norte",
        "Casabó",
        "Centro",
        "Cerrito",
        "Cerro",
        "Ciudad Vieja",
        "Colón",
        "Cordón",
        "Flor de Maroñas",
        "Goes",
        "Ituzaingó",
        "Jacinto Vera",
        "Jardines del Hipódromo",
        "La Blanqueada",
        "La Comercial",
        "La Figurita",
        "La Teja",
        "Larrañaga",
        "Las Acacias",
        "Lezica",
        "Malvín",
        "Malvín Norte",
        "Manga",
        "Maroñas",
        "Mercado Modelo",
        "Nuevo París",
        "Palermo",
        "Parque Batlle",
        "Parque Rodó",
        "Paso de la Arena",
        "Paso Molino",
        "Peñarol",
        "Piedras Blancas",
        "Pocitos",
        "Prado",
        "Punta Carretas",
        "Punta Gorda",
        "Reducto",
        "Sayago",
        "Tres Cruces",
        "Unión",
        "Villa Dolores",
        "Villa Española",
        "Villa Muñoz",
      ],
    },
  ],
  Paysandú: [{ name: "Paysandú" }],
  "Río Negro": [{ name: "Fray Bentos" }, { name: "Young" }],
  Rivera: [{ name: "Rivera" }],
  Rocha: [{ name: "Rocha" }, { name: "La Paloma" }, { name: "Punta del Diablo" }, { name: "Chuy" }],
  Salto: [{ name: "Salto" }],
  "San José": [{ name: "San José de Mayo" }, { name: "Ciudad del Plata" }],
  Soriano: [{ name: "Mercedes" }, { name: "Dolores" }],
  Tacuarembó: [{ name: "Tacuarembó" }, { name: "Paso de los Toros" }],
  "Treinta y Tres": [{ name: "Treinta y Tres" }],
};
